[package]
name = "orbweaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]

[dependencies]
serde = { version = "1.0.202", features = ["derive", "rc"] }

[features]
serde = []
default = ["serde"]
